scalar Date

interface Node {
  id: Int!
}

type Query {
  me: User
  # profile(userName: String)
}

type Mutation {
  register(registerInput: RegisterUserInput!): User
  #   login()
  #   createTier()
  #   createPost()
  #   subscribe(tierId: Int!)
}

type User implements Node {
  id: Int!
  email: String!
}

input RegisterUserInput {
  email: String!
  password: String!
}
